"""initial schema

Revision ID: 0af49831a9a7
Revises: 
Create Date: 2026-03-22 16:10:14.876739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0af49831a9a7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('centers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('contact_name', sa.String(length=100), nullable=True),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('center_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['center_id'], ['centers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('patients',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('patient_no', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('school_grade', sa.String(length=50), nullable=True),
    sa.Column('parent_myopia', sa.String(length=20), nullable=True),
    sa.Column('outdoor_hours_per_day', sa.Float(), nullable=True),
    sa.Column('near_work_hours_per_day', sa.Float(), nullable=True),
    sa.Column('center_id', sa.Integer(), nullable=False),
    sa.Column('enrolled_by', sa.Integer(), nullable=False),
    sa.Column('enrolled_at', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['center_id'], ['centers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['enrolled_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_no')
    )
    op.create_table('baseline_exams',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('exam_date', sa.Date(), nullable=False),
    sa.Column('od_sphere', sa.Float(), nullable=True),
    sa.Column('od_cylinder', sa.Float(), nullable=True),
    sa.Column('od_axis', sa.Integer(), nullable=True),
    sa.Column('od_va', sa.Float(), nullable=True),
    sa.Column('od_axial_length', sa.Float(), nullable=True),
    sa.Column('od_corneal_curvature_flat', sa.Float(), nullable=True),
    sa.Column('od_corneal_curvature_steep', sa.Float(), nullable=True),
    sa.Column('os_sphere', sa.Float(), nullable=True),
    sa.Column('os_cylinder', sa.Float(), nullable=True),
    sa.Column('os_axis', sa.Integer(), nullable=True),
    sa.Column('os_va', sa.Float(), nullable=True),
    sa.Column('os_axial_length', sa.Float(), nullable=True),
    sa.Column('os_corneal_curvature_flat', sa.Float(), nullable=True),
    sa.Column('os_corneal_curvature_steep', sa.Float(), nullable=True),
    sa.Column('lens_brand', sa.String(length=200), nullable=True),
    sa.Column('lens_od_addition', sa.Float(), nullable=True),
    sa.Column('lens_os_addition', sa.Float(), nullable=True),
    sa.Column('examiner_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['examiner_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_id')
    )
    op.create_table('follow_up_visits',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('visit_type', sa.String(length=10), nullable=False),
    sa.Column('visit_date', sa.Date(), nullable=False),
    sa.Column('od_sphere', sa.Float(), nullable=True),
    sa.Column('od_cylinder', sa.Float(), nullable=True),
    sa.Column('od_axis', sa.Integer(), nullable=True),
    sa.Column('od_va', sa.Float(), nullable=True),
    sa.Column('od_axial_length', sa.Float(), nullable=True),
    sa.Column('os_sphere', sa.Float(), nullable=True),
    sa.Column('os_cylinder', sa.Float(), nullable=True),
    sa.Column('os_axis', sa.Integer(), nullable=True),
    sa.Column('os_va', sa.Float(), nullable=True),
    sa.Column('os_axial_length', sa.Float(), nullable=True),
    sa.Column('wearing_hours_per_day', sa.Float(), nullable=True),
    sa.Column('compliance_good', sa.Boolean(), nullable=True),
    sa.Column('complaints', sa.Text(), nullable=True),
    sa.Column('examiner_notes', sa.Text(), nullable=True),
    sa.Column('examiner_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['examiner_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_id', 'visit_type', name='uq_visit_patient_type')
    )
    op.create_table('risk_scores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('progression_risk', sa.String(length=10), nullable=True),
    sa.Column('progression_confidence', sa.Float(), nullable=True),
    sa.Column('lens_response', sa.String(length=10), nullable=True),
    sa.Column('lens_response_confidence', sa.Float(), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('scored_at', sa.DateTime(), nullable=False),
    sa.Column('scored_by_model', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('risk_scores')
    op.drop_table('follow_up_visits')
    op.drop_table('baseline_exams')
    op.drop_table('patients')
    op.drop_table('users')
    op.drop_table('centers')
    # ### end Alembic commands ###
